version: '2'

services:
  nutch:
    container_name: nutch
    image: meabed/nutch
    ports:
          - 8899:8899
    links:
      - "hbase"
    volumes:
        - ./urls:/opt/nutch/urls
        - ./docker/nutch/gora.properties:/opt/nutch/conf/gora.properties:ro
        - ./docker/nutch/ivy.xml:/opt/apache-nutch-2.2.1/ivy/ivy.xml
        - ./docker/nutch/nutch-site.xml:/opt/apache-nutch-2.2.1/runtime/local/conf/nutch-site.xml
        - ./docker/hbase/hbase-site.xml:/opt/apache-nutch-2.2.1/runtime/local/conf/hbase-site.xml
    volumes_from:
      - data

#  cassandra:
#    container_name: cassandra
#    image: cassandra
#    ports:
#      - 9160:9160
#    volumes:
#      #- ./docker/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
#      - ./docker/cassandra/data:/var/lib/cassandra/

  hbase:
    image: banno/hbase-standalone

    volumes_from:
      - data
    volumes:
      - ./docker/hbase/hbase-site.xml:/opt/hbase/hbase-0.94.15-cdh4.7.0/conf/hbase-site.xml

  data:
    container_name: data_mounts
    image: busybox
    volumes:
      - ./docker/hbase/data:/data
