version: '2'

services:
  nutch:
    container_name: nutch
    image: diegogullo/nutch:2
    ports:
          - 8899:8899
          #ZooKeeper
          - 2181:2181
          - 39534:39534
          # NameNode (HDFS)
          - 8020:8020
          - 50070:50070
          - 9000:9000
          # DataNode (HDFS)
          - 50010:50010
          - 50020:50020
          - 50075:50075
          # SecondaryNameNode (HDFS)
          - 50090:50090
          # Trackers
          - 50030:50030
          - 50060:50060
          #HBASE
          - 6000:6000
          - 60010:60010
          - 60020:60020
          - 60030:60030
          # Thrift
          - 9090:9090
          - 9095:9095
#    links:
#      - "hbase"
    volumes:
        - ./urls:/opt/nutch/urls
        - ./docker/nutch/gora.properties:/opt/nutch/conf/gora.properties
        - ./docker/nutch/ivy.xml:/opt/apache-nutch-2.x/ivy/ivy.xml
        - ./docker/nutch/nutch-site.xml:/opt/nutch/conf/nutch-site.xml
        - ./docker/hbase/hbase-site.xml:/opt/nutch/conf/hbase-site.xml
    volumes_from:
      - data
    environment:
      - HBASE_HOME=/opt/hbase
      - HADOOP_CLASSPATH="/opt/hbase/lib/*"

#  cassandra:
#    container_name: cassandra
#    image: cassandra
#    ports:
#      - 9160:9160
#    volumes:
#      #- ./docker/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
#      - ./docker/cassandra/data:/var/lib/cassandra/

#  hbase:
#    image: banno/hbase-standalone
#    environment:
#      - REDIS_HOST=appcache
#      - REDIS_PORT=6379
#      - CACHE_DRIVER=redis
#      - SESSION_DRIVER=redis
#      - OKTA_API_KEY=001ZYzCLHpU-ozUDDHITYJKNyQL8aHEoc1lvxsK7ke
#      - OKTA_BASE_URI=https://kobaltmusic.okta-emea.com
#      - APP_ENV=local # to be changed with env variable soon
#      - APP_DEBUG=true
#      - APP_KEY=y3sHANM1WWa8DsVLKYqYdLzLRd1sYm2Z
#    volumes_from:
#      - data
#    volumes:
#      - ./docker/hbase/hbase-site.xml:/opt/hbase/hbase-0.94.15-cdh4.7.0/conf/hbase-site.xml
#      - ./docker/hbase/data:/data

  data:
    container_name: data_mounts
    image: busybox
    volumes:
      - ./docker/hbase/data:/data